inp = int(input('Please tell me your age: '))
print(f'You are currently {inp} years old.')
print(f"In 10 years, you'll be {inp + 10} years old.")
print(f"In 20 years, you'll be {inp + 20} years old.")
print(f"In 30 years, you'll be {inp + 30} years old.")
